# Generated by Django 2.2.4 on 2019-11-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpractice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='url',
        ),
    ]
