# Generated by Django 2.2.4 on 2019-11-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpractice', '0004_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
